name: Node

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-2019

    strategy:
      matrix:
        node: [ '14', '10' ]

    name: ${{ matrix.node }} (Windows)
    steps:
    - name: Checkout Commit
      uses: actions/checkout@v1
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    # needed so that Node 10 downloads a compatible less-loader version
    - name: Clear lock file
      run: del yarn.lock
    - name: yarn install
      run: yarn --ignore-engines
    - name: run tests
      run: yarn test
